In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("C:/Users/ACER/Downloads/data_demo.csv")

In [3]:
df=df.drop(['short_description','price_usd','order_count','inventory_status','is_visible','stock_item_qty','stock_item_max_sale_qty','product_name'],axis=1)
df

,id,sku,price,list_price,discount,discount_rate,review_count,brand_id,brand_name,quantity_sold,rating_average,category_type,category_id
0,435870.0,8.006427e+12,808000.0,954556.0,146556.0,15.0,808.0,145924.0,Ensure,28546.0,4.8,do-choi-me-be,2549
1,57044926.0,3.629907e+12,919000.0,1078000.0,159000.0,15.0,302.0,149737.0,Pediasure,2764.0,5.0,do-choi-me-be,2549
2,24030105.0,5.781212e+12,599000.0,733282.0,134282.0,18.0,528.0,149737.0,Pediasure,8055.0,4.8,do-choi-me-be,2549
3,24028050.0,9.863682e+12,1005000.0,1238569.0,233569.0,19.0,716.0,149737.0,Pediasure,12707.0,4.8,do-choi-me-be,2549
4,24026125.0,2.973806e+12,1239000.0,1426944.0,187944.0,13.0,257.0,149741.0,Glucerna,2837.0,5.0,do-choi-me-be,2549
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2785,213710314.0,4.601854e+12,1019000.0,1019000.0,0.0,0.0,1.0,27464.0,TP-Link,1.0,5.0,may-anh,1801
2786,199532725.0,6.558414e+12,1350000.0,2000000.0,650000.0,33.0,11.0,545395.0,ASPORT,31.0,4.5,may-anh,1801
2787,195864060.0,5.237590e+12,2000000.0,2000000.0,0.0,0.0,43.0,228755.0,Andbon,205.0,4.8,may-anh,1801
2788,68454398.0,3.292439e+12,129999.0,129999.0,0.0,0.0,11.0,193617.0,VSGO,31.0,4.6,may-anh,1801
2789,14578165.0,8.969819e+12,648999.0,648999.0,0.0,0.0,44.0,153086.0,RAVPower,134.0,4.8,may-anh,1801

In [4]:
Q1 = df['quantity_sold'].quantile(0.25)
Q3 = df['quantity_sold'].quantile(0.75)
IQR = Q3 - Q1
IQR
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df=df[(df['quantity_sold'] > lower_bound) & (df['quantity_sold'] < upper_bound)]

In [5]:
df=df.drop(['brand_name','category_type'],axis=1)

In [6]:
y=df['quantity_sold']
X=df.drop(['quantity_sold'],axis=1)

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X=scaler.fit_transform(X)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [9]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

def regression_report(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = mean_squared_error(y_true, y_pred, squared=False)
    r2 = r2_score(y_true, y_pred)

    print("Regression Report:")
    print("Mean Absolute Error (MAE):", mae)
    print("Mean Squared Error (MSE):", mse)
    print("Root Mean Squared Error (RMSE):", rmse)
    print("R-squared (R^2):", r2)

In [10]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(random_state=2023)
rf.fit(X_train, y_train)
y_pred_forest=rf.predict(X_test)
regression_report(y_test, y_pred_forest)

Regression Report:
Mean Absolute Error (MAE): 47.095585331452746
Mean Squared Error (MSE): 8218.738336953456
Root Mean Squared Error (RMSE): 90.65725749741968
R-squared (R^2): 0.84309920061867

In [14]:
y_pred=rf.predict(X)

In [15]:
df['prediction']=y_pred

In [17]:
df=df.sort_values(by='prediction',ascending=False)

In [18]:
df

,id,sku,price,list_price,discount,discount_rate,review_count,brand_id,quantity_sold,rating_average,category_id,prediction
1920,153066085.0,6.009850e+12,28000.0,30000.0,2000.0,7.0,193.0,21437.0,1098.0,4.8,1883,1024.48
1812,67619329.0,9.813911e+12,108000.0,108000.0,0.0,0.0,283.0,18991.0,1071.0,4.8,1846,1015.78
2423,50392581.0,8.081831e+12,450000.0,450000.0,0.0,0.0,400.0,27561.0,1038.0,4.7,8594,978.24
564,113457048.0,7.350389e+12,2219000.0,5355000.0,3136000.0,59.0,362.0,48077.0,1004.0,4.7,1882,972.32
486,105035792.0,4.058004e+12,989000.0,1499000.0,510000.0,34.0,292.0,19813.0,987.0,4.7,1882,963.10
...,...,...,...,...,...,...,...,...,...,...,...,...
1474,202344015.0,3.469244e+12,600000.0,1200000.0,600000.0,50.0,1.0,153494.0,1.0,5.0,27616,1.14
2081,201950753.0,6.942459e+12,209002.0,232225.0,23223.0,10.0,1.0,111461.0,1.0,4.0,17166,1.12
2069,213702120.0,7.300834e+12,342000.0,684000.0,342000.0,50.0,1.0,8078371.0,1.0,5.0,17166,1.11
2014,109442576.0,8.472001e+12,216000.0,240000.0,24000.0,10.0,1.0,111461.0,1.0,4.0,17166,1.08
2024,91790229.0,4.515121e+12,190000.0,190000.0,0.0,0.0,1.0,111461.0,1.0,4.0,17166,1.06

In [19]:
df['id'].to_csv("C:/Users/ACER/Downloads/sorted_id.csv",index=False)

In [20]:
import requests
import time
import random
from tqdm import tqdm

In [21]:
cookies = {
  "_trackity": "875b2ce4-212f-5cce-04d9-cc6ec84bf2f7",
  "_gcl_au": "1.1.793529080.1679215808",
  "_fbp": "fb.1.1679215808224.1068958507",
  "__uidac": "f163acf12945398651d700901d47bd14",
  "__RC": "5",
  "__R": "3",
  "_hjSessionUser_522327": "eyJpZCI6ImQ0MWUxODRkLTgzMzYtNWQ1Zi1hMmJiLWFhZGYyY2JmMWZmYiIsImNyZWF0ZWQiOjE2NzkyMTU4MDg0ODUsImV4cXVlfQ==",
  "__tb": "0",
  "__IP": "1906395470",
  "TOKENS": "{\"access_token\":\"l6HVuhRjUtfPKE2A8iZIL0Dwb4xYazs5\"}",
  "_gid": "GA1.2.1511626058.1686905968",
  "_hjSession_522327": "eyJpZCI6ImFjMjkwNDY1LTgyOGQtNDlmYy1iYTI1LTgwMzkwOWNhODUwOSIsImNyZWF0ZWQiOjE2ODY5MDU5NzE5MjgsImluU2FtcGxlIjpmYWxzZX0=",
  "_hjAbsoluteSessionInProgress": "0",
  "__iid": "749",
  "__su": "0",
  "delivery_zone": "Vk4wMzkwMDYwMDE=",
  "tiki_client_id": "774354415.1679215804",
  "_hjIncludedInSessionSample_522327": "0",
  "amp_99d374": "Bdfp1skWNI3tqexv6d9H87...1h31q5ut9.1h31r1brn.1a.2k.3u",
  "_ga": "GA1.1.774354415.1679215804",
  "__uif": "__uid%3A1607895402883714693%7C__ui%3A-1%7C__create%3A1640789540",
  "cto_bundle": "zCBANF9hWnFWSnkxRXRYMGNnJTJCUkZGbVpsNVVKOUdQRE1IdWNMWVZ0UDdSbzg5QkV4NHQwd3hmdVFBTlNMbjE0RmwxdTZ0WUIwSENiNWdSaGtDbEtVSElhJTJGQWJyanVDNnhhTmw2dEdlN0JYR2FLSUlmJTJGcldVVDY1Y09VODM1NGNKZzZtUjNUM1R1YVV2S0NkWmdUVmhtJTJGc0MxUSUzRCUzRA",
  "_gat": "1",
  "_ga_GSD4ETCY1D": "GS1.1.1686909427.4.1.1686910516.60.0.0",
}

In [22]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
    'Accept': 'application/json, text/plain, */*',
    'Accept-Language': 'vi-VN,vi;q=0.9,en-US;q=0.8,en;q=0.7',
    'Referer': 'https://tiki.vn/may-tinh-bang-samsung-galaxy-tab-s6-lite-2022-4gb-64gb-sm-p615-da-kich-hoat-bao-hanh-dien-tu-hang-chinh-hang-p203949614.html?itm_campaign=CTP_YPD_TKA_PLA_UNK_ALL_UNK_UNK_UNK_UNK_X.216226_Y.1798546_Z.3602913_CN.Tab-s6-Lite&itm_medium=CPC&itm_source=tiki-ads&spid=203949620',
    'x-guest-token': 'l6HVuhRjUtfPKE2A8iZIL0Dwb4xYazs5',
    'Connection': 'keep-alive',
    'TE': 'Trailers',
}

In [23]:
params = {
    'platform': 'web',
    'spid': '203949620',
}

In [24]:
def parser_product(json):
    d = dict()
    d['id'] = json.get('id')
    d['sku'] = json.get('sku')
    d['short_description'] = json.get('short_description')
    d['price'] = json.get('price')
    d['list_price'] = json.get('list_price')
    d['price_usd'] = json.get('price_usd')
    d['discount'] = json.get('discount')
    d['discount_rate'] = json.get('discount_rate')
    d['review_count'] = json.get('review_count')
    d['order_count'] = json.get('order_count')
    d['inventory_status'] = json.get('inventory_status')
    d['is_visible'] = json.get('is_visible')
    d['stock_item_qty'] = json.get('stock_item').get('qty')
    d['stock_item_max_sale_qty'] = json.get('stock_item').get('max_sale_qty')
    d['product_name'] = json.get('meta_title')
    d['brand_id'] = json.get('brand').get('id')
    d['brand_name'] = json.get('brand').get('name')
    d['quantity_sold']=json.get('quantity_sold').get('value')
    d['rating_average']=json.get('rating_average')
    return d

In [26]:
df_id = pd.read_csv("C:/Users/ACER/Downloads/sorted_id.csv")
p_ids = df_id.id.to_list()

results=[]
for pid in tqdm(p_ids,total=len(p_ids)):
    reponse=requests.get('https://tiki.vn/api/v2/products/{}'.format(pid),headers=headers,params=params,cookies=cookies)
    if reponse.status_code==200:
        try:
            results.append(parser_product(reponse.json()))
        except:
            p_ids.remove(pid)
            continue
df_product=pd.DataFrame(results)
df_product.to_csv("C:/Users/ACER/Downloads/product_data.csv",index=False)

 50%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ                                       | 1182/2363 [05:41<05:41,  3.46it/s]